name = "littleman.co"
license = "MIT"
description = "An implementation of the "basic bootstrap" theme from Zachary Betz"
homepage = "https://github.com/littlemanco/www.littleman.co"
tags = ["home", "blog", "tags", "bootstrap", "minimal", "clean", "simple"]
features = ["home", "blog", "tags", "bootstrap", "minimal", "clean", "simple"]
min_version = "0.48"

