apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  labels:
    app: {{ template "www-littleman-co.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "www-littleman-co.fullname" . }}
spec:
  commonName: littleman.co
  dnsNames:
  - www.littleman.co
  - littleman.co
  - api.littleman.co
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: littleman-co-tls