---
kind: "pipeline"
name: "web"
steps:
  - name: "hugo"
    image: "quay.io/littlemanco/hugo:1.0.0"

trigger:
  branch:
    - "master"
  event:
    - "pull_request"
---
kind: "pipeline"
name: "deploy"

steps:
  - name: "hugo"
    image: "quay.io/littlemanco/hugo:1.0.0"
  - name: "container"
    image: "plugins/gcr"
    settings:
      repo: "littleman-co/www-littleman-co"
      dockerfile: "build/container/Dockerfile"
      json_key:
        from_secret: "GOOGLE_SERVICE_ACCOUNT"
  - name: "deploy"
    image: "quay.io/littlemanco/helm"
    environment:
      B64_GOOGLE_SERVICE_ACCOUNT:
        from_secret: "B64_GOOGLE_SERVICE_ACCOUNT"
      GOOGLE_APPLICATION_CREDENTIALS: "/tmp/.google-service-account.json"
      GOOGLE_PROJECT_NAME: "littleman-co"
      GOOGLE_PROJECT_REGION: "europe-west1-d"
      GOOGLE_GKE_CLUSTER_NAME: "littleman-co"
      KUBERNETES_NAMESPACE: "www-littleman-co"
    commands:
      - "echo $B64_GOOGLE_SERVICE_ACCOUNT | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS"
      - "gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS"
      - "gcloud config set project $GOOGLE_PROJECT_NAME"
      - "gcloud container clusters get-credentials --zone $GOOGLE_PROJECT_REGION $GOOGLE_GKE_CLUSTER_NAME"
      - "helm upgrade --install --namespace www-littleman-co www-littleman-co deploy/helm"

trigger:
  branch:
    - "master"
  event:
    - "push"
