---
kind: "pipeline"
name: "lint"
steps:
  - name: "lint"
    image: "gcr.io/littleman-co/www-littleman-co--build:6529600"
    commands:
      - /usr/local/bin/robo lint

trigger:
  # Execute this process every time a new pull request is opened
  event:
    - pull_request
---
kind: "pipeline"
name: "unit-test"
steps:
  - name: "test"
    image: "gcr.io/littleman-co/www-littleman-co--build:6529600"
    commands:
      - /usr/local/bin/robo test:unit
trigger:
  event:
    - pull_request
---
kind: "pipeline"
name: "integration-test"
steps:
  - name: "test"
    image: "gcr.io/littleman-co/www-littleman-co--build:6529600"
    commands:
      - /usr/local/bin/robo test:integration
trigger:
  event:
    - pull_request
depends_on:
  - lint
  - unit-test
---
kind: "pipeline"
name: "smoke-test"
steps:
  - name: "test"
    image: "gcr.io/littleman-co/www-littleman-co--build:6529600"
    commands:
      - /usr/local/bin/robo test:smoke
trigger:
  event:
    - pull_request
depends_on:
  - lint
  - unit-test
---
kind: "pipeline"
name: "stress-test"
steps:
  - name: "test"
    image: "gcr.io/littleman-co/www-littleman-co--build:6529600"
    commands:
      - /usr/local/bin/robo test:stress
trigger:
  event:
    - pull_request
depends_on:
  - lint
  - unit-test
---
kind: "pipeline"
name: "container"
steps:
  - name: "container"
    image: "gcr.io/littleman-co/www-littleman-co--build:6529600"
    environment:
      GOOGLE_SERVICE_ACCOUNT:
        from_secret: GOOGLE_SERVICE_ACCOUNT
    # Required to build container
    privileged: true
    commands:
      # Enable img to push to docker registry
      - img login -u _json_key -p "$GOOGLE_SERVICE_ACCOUNT" https://gcr.io
      - /usr/local/bin/robo application:compile
      - /usr/local/bin/robo container:build --container=web
      - /usr/local/bin/robo container:push --container=web

trigger:
  branch:
    - master
  event:
    - push
---
kind: "pipeline"
name: "production"
steps:
  - name: "deploy" 
    image: "gcr.io/littleman-co/www-littleman-co--build:6529600" 
    environment: 
      B64_GOOGLE_SERVICE_ACCOUNT: 
        from_secret: "B64_GOOGLE_SERVICE_ACCOUNT" 
      GOOGLE_APPLICATION_CREDENTIALS: "/tmp/.google-service-account.json" 
      GOOGLE_PROJECT_NAME: "littleman-co" 
      GOOGLE_PROJECT_REGION: "europe-west1-d" 
      GOOGLE_GKE_CLUSTER_NAME: "littleman-co" 
      KUBERNETES_NAMESPACE: "www-littleman-co" 
    commands: 
      - "echo $B64_GOOGLE_SERVICE_ACCOUNT | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS" 
      - "gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS" 
      - "gcloud config set project $GOOGLE_PROJECT_NAME" 
      - "gcloud container clusters get-credentials --zone $GOOGLE_PROJECT_REGION $GOOGLE_GKE_CLUSTER_NAME" 
      - |
          helm upgrade \
            --install \
            --namespace www-littleman-co \
            --wait \
            --set="pod.web.image=gcr.io/littleman-co/www-littleman-co--web:$(git rev-parse --short HEAD)" \
            www-littleman-co \
            deploy/helm
trigger:
  branch:
    - master
depends_on:
  - container
---
kind: "pipeline"
name: "rollback"
steps:
  - name: "rollback"
    image: "gcr.io/littleman-co/www-littleman-co--build:6529600"
    commands:
      - /usr/local/bin/robo rollback --environment=production
trigger:
  event:
    - rollback
  target:
    - production
  branch:
    - master
