---
baseURL: https://www.littleman.co
languageCode: en-us
title: littleman.co
theme: littleman-co
googleAnalytics: "UA-53227254-4"
publishDir: "web"

pygmentsCodefences: true
pygmentsCodefencesGuessSyntax: true
# See https://xyproto.github.io/splash/docs/all.html for more styles
pygmentsStyle: pygments

taxonomies:
  contributor: "contributors"
  tag: "tags"
  category: "categories"

permalinks:
  post: /:filename/

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Articles
      url: /articles/
      weight: 2
    - name: "Docs"
      url: "/documentation"
      weight: 3

params:
  includeBootstrapJs: false
  showActiveNav: true
  containerMaxWidth: 700px
  dateFormat: Jan 2, 2006
  homeText: |
    **Simple, Beautiful web development.**

    The best way to get started working with us at here at littleman.co is to email the support mail:

    [support@littleman.co](support@littleman.co?subject=Request%20for%20further%20information)

    From there we can discuss whether we can help. Try and be as detailed as you can; to preserve our concentration and
    try and be as efficient as possible we generally only check email 1x per 24 hour period.

    [Objectives (2019)](/objectives-and-key-results/)
  footerText: |
    ⓒ Andrew Howden, 2019 · We are on [Twitter](https://twitter.com/littlemanco),
    [GitHub](https://github.com/littlemanco) and [Medium](https://medium.com/littlemanco).
  hideFooter: false
