---
categories: ["Documentation"]
date: 2019-03-10
description: "The places that littleman.co publishes, as well as guidelines for those publications"
slug: "media"
tags: ["media", "articles", "publications"]
title: "Media"
---

Media is any form of publication or distribution that littleman.co contributes to, distributes or otherwise partakes 
in. Currently there is:

- https://www.littleman.co/articles/[The Website]
- https://dev.to/[dev.to]
- https://hackernoon.com/[Hacker Noon]
- https://medium.com/littlemanco[Medium]
- https://twitter.com/littlemanco[Twitter]

Articles are canonically published on the https://www.littleman.co/[littleman.co website], but can be syndicated on any
provider that allows a canonical link back littleman.co

== Taxonomy

Long form (160+ character) publications must be allocated a canonical category from the following:

|===
| Type                   | Description                                                                                       | Publication Stream

| Labs                   | A review of a new or experimental technology, not yet used in a production environment.           | Medium
| Case Study             | A review of a previous technical or process intervention focussed on return on investment         | Medium, Website
| Technical Analysis     | A general description of a technical implementation across many systems                           | Medium, Documentation
| Deep Dive              | An in depth discussion of a given technical problem and solution                                  | Medium
| Philosophy             | A discussion of the underlying beliefs behind the software development                            | Medium, Website
|===

== Publications

=== General Process

When writing a (long form) post, the process is as follows:

1. Write the post up & publish it to littleman.co.
2. Verify the content against http://www.hemingwayapp.com/[the Hemingway app]
3. Wait ~24 hours
4. Re-read the content
5. Publish the content to the distribution network

A template for writing the article is below:

[source]
----
---
categories: []
// Uncomment one:
//  - "Labs"
//  - "Case Study"
//  - "Technical Analysis"
//  - "Deep Dive"
//  - "Philosophy"

// Date in the form of "1970-01-01"
date: __TODO__

// A description used in search results, social media tags
description: "__DESCRIPTION__"

// How the URL should appear
slug: "__this-is-a-url__"

// A list of things that this article should talk about
//
// Try and pick ~ 4 tags. The list of previously used tags is at the following URL:
// https://www.littleman.co/tags/
//
// When syndicated, the category should be an additional tag.
tags: 
  - "__TAG__"
  - "__TAG__"
  - "__TAG__"
  - "__TAG__"

// The header of the article
title: "__TITLE__"

// What GitHub issue the article is tracked by
github-issue: 11

// The path to images suitable for use with the article
//
// The images work best at 1000x420
images:
  - "/images/headers/architecting-a-software-system-for-malleability.png"

// Who contributed to the article, written in the order of their contributions.
contributors:
  - "Andrew Howden"
---

== __TITLE__

// Content
----
